spring.application.name=springCai

#dubbo
application.name=springWeb-provider
register.address=zookeeper://127.0.0.1:2181
cache=./opt/dubbo/cache
name=dubbo

#\u6570\u636E\u6E90\u4E00
spring.datasource.primary.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.primary.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.primary.url=jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
spring.datasource.primary.username=root
spring.datasource.primary.password=C89!JH241@$

spring.datasource.primary.hikari.auto-commit=true
spring.datasource.primary.hikari.initialization-fail-timeout=20000
spring.datasource.primary.hikari.connection-timeout=20000
spring.datasource.primary.hikari.connection-init-sql=select 1
spring.datasource.primary.hikari.connection-test-query=select 1
spring.datasource.primary.hikari.max-lifetime=3600000
spring.datasource.primary.hikari.maximum-pool-size=20
spring.datasource.primary.hikari.minimum-idle=10
spring.datasource.primary.hikari.idle-timeout=600000

mybatis.mapper-locations-primary=classpath*:mapper/*.xml

#\u6570\u636E\u6E90\u4E8C
spring.datasource.secondary.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.secondary.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.secondary.url=jdbc:mysql://127.0.0.1:3306/mmc_dataSource?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
spring.datasource.secondary.username=root
spring.datasource.secondary.password=C89!JH241@$

spring.datasource.secondary.hikari.auto-commit=true
spring.datasource.secondary.hikari.initialization-fail-timeout=20000
spring.datasource.secondary.hikari.connection-timeout=20000
spring.datasource.secondary.hikari.connection-init-sql=select 1
spring.datasource.secondary.hikari.connection-test-query=select 1
spring.datasource.secondary.hikari.max-lifetime=3600000
spring.datasource.secondary.hikari.maximum-pool-size=20
spring.datasource.secondary.hikari.minimum-idle=10
spring.datasource.secondary.hikari.idle-timeout=600000

mybatis.mapper-locations-secondary=classpath*:mapperSecondary/*.xml

my.getValue.test=\u8521\u8FDB\u8F89