/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_springCai_nativeTest_CryptoUtils */

#ifndef _Included_cn_com_springCai_nativeTest_CryptoUtils
#define _Included_cn_com_springCai_nativeTest_CryptoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_springCai_nativeTest_CryptoUtils
 * Method:    encrypt
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_com_springCai_nativeTest_CryptoUtils_encrypt
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     cn_com_springCai_nativeTest_CryptoUtils
 * Method:    sayHell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_springCai_nativeTest_CryptoUtils_sayHell
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
